//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AREAS.calcular {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="calcular.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        AREAS.calcular.HelloWorldResponse HelloWorld(AREAS.calcular.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<AREAS.calcular.HelloWorldResponse> HelloWorldAsync(AREAS.calcular.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUADRADO", ReplyAction="*")]
        int CUADRADO(int Lado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CUADRADO", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CUADRADOAsync(int Lado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TRIANGULO", ReplyAction="*")]
        int TRIANGULO(int Base, int Altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TRIANGULO", ReplyAction="*")]
        System.Threading.Tasks.Task<int> TRIANGULOAsync(int Base, int Altura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CIRCULO", ReplyAction="*")]
        double CIRCULO(double Radio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CIRCULO", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CIRCULOAsync(double Radio);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public AREAS.calcular.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AREAS.calcular.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public AREAS.calcular.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AREAS.calcular.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : AREAS.calcular.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<AREAS.calcular.WebServiceSoap>, AREAS.calcular.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AREAS.calcular.HelloWorldResponse AREAS.calcular.WebServiceSoap.HelloWorld(AREAS.calcular.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            AREAS.calcular.HelloWorldRequest inValue = new AREAS.calcular.HelloWorldRequest();
            inValue.Body = new AREAS.calcular.HelloWorldRequestBody();
            AREAS.calcular.HelloWorldResponse retVal = ((AREAS.calcular.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AREAS.calcular.HelloWorldResponse> AREAS.calcular.WebServiceSoap.HelloWorldAsync(AREAS.calcular.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<AREAS.calcular.HelloWorldResponse> HelloWorldAsync() {
            AREAS.calcular.HelloWorldRequest inValue = new AREAS.calcular.HelloWorldRequest();
            inValue.Body = new AREAS.calcular.HelloWorldRequestBody();
            return ((AREAS.calcular.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int CUADRADO(int Lado) {
            return base.Channel.CUADRADO(Lado);
        }
        
        public System.Threading.Tasks.Task<int> CUADRADOAsync(int Lado) {
            return base.Channel.CUADRADOAsync(Lado);
        }
        
        public int TRIANGULO(int Base, int Altura) {
            return base.Channel.TRIANGULO(Base, Altura);
        }
        
        public System.Threading.Tasks.Task<int> TRIANGULOAsync(int Base, int Altura) {
            return base.Channel.TRIANGULOAsync(Base, Altura);
        }
        
        public double CIRCULO(double Radio) {
            return base.Channel.CIRCULO(Radio);
        }
        
        public System.Threading.Tasks.Task<double> CIRCULOAsync(double Radio) {
            return base.Channel.CIRCULOAsync(Radio);
        }
    }
}
